# Generated by Django 2.2.3 on 2019-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
